<?php
/**
 * @file
 */

/**
 * Implements hook_views_query_alter().
 * Adding term filter for subsites.
 */
function stanford_lbre_helper_views_query_alter(&$view, &$query) {
  if (($view->name == 'stanford_events_views' && $view->current_display == 'block')
  || ($view->name == 'stanford_news' && $view->current_display == 'block_2_item_recent_news_list')
  || ($view->name == 'stanford_person_vpsa' && $view->current_display == 'block_staff')
  || ($view->name == 'stanford_slides_full_width_banner' && $view->current_display == 'block')) {
    if (arg(0) == 'node') {
      $nid = arg(1);
      $node = node_load($nid);
      $node_tid = $node->field_stanford_subsite_sub_tags[LANGUAGE_NONE][0]['tid'];
      $tids = array_keys(taxonomy_allowed_values(field_info_field('field_stanford_subsite_sub_tags')));
      if (in_array($node_tid, $tids)) {
        $join = new views_join();
        $join->table = 'taxonomy_index';
        $join->field = 'nid';
        $join->left_table = 'node';
        $join->left_field = 'nid';
        $join->type = 'INNER';
        //add the join the the view query
        $view->query->add_relationship('taxonomy_index',$join,'node');
    
        //add the where
        $view->query->where[1]['conditions'][] = array(
            'field' => 'taxonomy_index.tid',
            'value' => $node_tid,
            'operator' => '='
        );
      }
    }
  }
  elseif (($view->name == 'guides_filter' && $view->current_display == 'block')) {
    if (arg(0) == 'node') {
      $current_path = url(current_path(), array('relative' => TRUE));
      $subsite_path = explode('/', $current_path);
      $path = drupal_lookup_path("source", $subsite_path[1]);
      $node = menu_get_object("node", 1, $path);
      $node_tid = $node->field_stanford_subsite_sub_tags[LANGUAGE_NONE][0]['tid'];
      $tids = array_keys(taxonomy_allowed_values(field_info_field('field_stanford_subsite_sub_tags')));
      $related_tids = array_keys(taxonomy_allowed_values(field_info_field('field_s_guides_relates_to')));
      if (in_array($node_tid, $tids) || in_array($node_tid, $related_tids)) {
        $join = new views_join();
        $join->table = 'field_data_field_stanford_subsite_sub_tags';
        $join->field = 'entity_id';
        $join->left_table = 'node';
        $join->left_field = 'nid';
        $join->type = 'INNER';
        //add the join the the view query
        $view->query->add_relationship('field_data_field_stanford_subsite_sub_tags',$join,'node');
        
        //add the where
        $view->query->where[2]['conditions'][] = array(
            'field' => 'field_data_field_stanford_subsite_sub_tags.field_stanford_subsite_sub_tags_tid',
            'value' => $node_tid,
            'operator' => '='
        );
        
        $join = new views_join();
        $join->table = 'field_data_field_s_guides_relates_to';
        $join->field = 'entity_id';
        $join->left_table = 'node';
        $join->left_field = 'nid';
        $join->type = 'INNER';
        //add the join the the view query
        $view->query->add_relationship('field_data_field_s_guides_relates_to',$join,'node');
        
        //add the where
        $view->query->where[2]['conditions'][] = array(
            'field' => 'field_data_field_s_guides_relates_to.field_s_guides_relates_to_tid',
            'value' => array($node_tid => $node_tid),
            'operator' => 'IN'
        );
        // Using OR since we want guides specifically and those that are related.
        $view->query->where[2]['type'] = 'OR';
        // Using distinct since multiple terms matching will cause duplicates.
        $query->distinct = TRUE;
      }
    }
  }
}

function stanford_lbre_helper_block_info_alter(&$blocks, $theme, $code_blocks) {
  // Remove the caching on subsite blocks.
  //$blocks['views']['stanford_events_views-block']['cache'] = DRUPAL_NO_CACHE;
  // block_2_item_recent_news_list
  //$blocks['views']['f73ff55b085ea49217d347de6630cd5a']['cache'] = DRUPAL_NO_CACHE;
  // block_staff
  //$blocks['views']['cfd61adc4b7db1bdee953a216e12302c']['cache'] = DRUPAL_NO_CACHE;
  // stanford_slides_full_width_banner
  //$blocks['views']['9530832697bc4866adbecb898b8ca7db']['cache'] = DRUPAL_NO_CACHE;
  // Disabling cache on block that gets installed within module causes integrity constrain violation(guides_filter-block).
  //$blocks['views']['guides_filter-block ']['cache'] = DRUPAL_NO_CACHE;
}
